### ISSUE TITLE
Add an option to allow for hierarchies of objects.

### ISSUE THREAD

**Issue by davesag** [davesag/acts_as_read_only_i18n_localised#3]
```
    en:
      categories:
        fruits:
          name: Great fresh fruit
          description: Our fantastic range of seasonal and local fresh fruit will delight you.
        vegetables:
          name: Farm fresh veggies
          description: Our locally grown and freshly harvested veggies are simply delicious.
        meats:
          name: Farm-fresh seasonal meat
          description: >-
            Loved in life then lightly killed, our meat is locally sourced from small farms
            that meet our demanding standards.
```

could become

```
    en:
      categories:
        fruits:
          name: Great fresh fruit
          description: Our fantastic range of seasonal and local fresh fruit will delight you.
          categories:
             citrus:
               name: Tangy Citrus
               description: All the fresh winter fruit you can eat!
```

and in `db/seeds.rb` you'd go (crappy example, but it shows how it would work)

```
I18n.t(:categories).each do |key, data|
  cat = Category.where(slug: key).first_or_create!
  if data[:categories]
    data[:categories].each do |sub_key, sub_data|
      slug = "#{key}.categories.#{sub_key}"
      Category.where(slug: slug, parent: cat).first_or_create!
    end
  end
end
```
